
<!--TOC START-->
<table cellSpacing="0" cellPadding="0" width="148" border="0" style="TABLE-LAYOUT: fixed">
    <tr>
        <td height="12">
            &nbsp;
        </td>
    </tr>
    <tr>
        <td class="menuHeader">
            CONTENTS
        </td>
    </tr>
    <tr>
        <!--BEGIN ONE LINE-->
        <td height="3" valign="center"><img src="images/blue_dotted_line.gif" width="150" height="3" alt="" border="0"></td>
        <!--END ONE LINE-->
    </tr>
    <tr>
        <td>

            <div style="padding:0,0,4,0"><b><a href="default.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Introduction</a></b></div>
			<div style="padding:0,0,4,0"><b><a href="login.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Logging In</a></b></div>

            <div style="padding:0,0,4,0"><b><a href="databases.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Databases</a></b></div>
            &nbsp; <a href="createdatabase.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Creating</a><br>
            &nbsp; <a href="tables.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Editing</a><br>
            &nbsp; <a href="deletedatabase.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Deleting</a><br>
            &nbsp; <a href="querydatabase.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Querying</a><br>
            &nbsp; <a href="import.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Importing</a><br>
            &nbsp; <a href="export.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Exporting</a><br>
            &nbsp; <a href="databaseproperties.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Properties</a><br>
            &nbsp; <a href="databaseroles.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Roles</a><br>
            <div style="padding:0,0,4,0">&nbsp; <a href="databaseusers.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Users</a><br></div>

            <div style="padding:0,0,4,0"><b><a href="tables.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Tables</a></b></div>
            &nbsp; <a href="createtable.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Creating</a><br>
            &nbsp; <a href="columns.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Editing</a><br>
            &nbsp; <a href="deletetable.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Deleting</a><br>
            &nbsp; <a href="querydatabase.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Querying</a><br>
            <div style="padding:0,0,4,0">&nbsp; <a href="renametable.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Renaming</a></div>

            <div style="padding:0,0,4,0"><b><a href="columns.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Columns</a></b></div>
            &nbsp; <a href="editcolumn.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Creating</a><br>
            &nbsp; <a href="editcolumn.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Editing</a><br>
            <div style="padding:0,0,4,0">&nbsp; <a href="deletecolumn.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Deleting</a></div>

            <div style="padding:0,0,4,0"><b><a href="storedprocedures.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Stored Procedures</a></b></div>
            &nbsp; <a href="createstoredprocedure.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Creating</a><br>
            &nbsp; <a href="editstoredprocedure.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Editing</a><br>
            <div style="padding:0,0,4,0">&nbsp; <a href="deletestoredprocedure.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Deleting</a></div>

            <div style="padding:0,0,4,0"><b><a href="security.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Security</a></b></div>
            &nbsp; <a href="ServerLogins.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Server Logins</a><br>
            <div style="padding:0,0,4,0">&nbsp; <a href="ServerRoles.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Server Roles</a><br></div>
            
            <div style="padding:0,0,4,0"><b><a href="error.aspx" class="leftMenu" onMouseOver="this.style.color='#ffffff';" onMouseOut="this.style.color='#000000';" >Errors</a></b></div>

        </td>
    </tr>
</table>
<!--TOC END-->